# makefile for lab5
all: TestProgram.exe

TestProgram.exe: Program.cpp Image.cpp Filter.cpp GrayScaleDilation.cpp
	g++ -g -o TestProgram.exe Program.cpp Image.cpp Filter.cpp GrayScaleDilation.cpp -lm

